# Generated by Django 5.1.6 on 2025-02-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='item_name', max_length=250)),
                ('initial_price', models.FloatField()),
                ('step_price', models.FloatField(default=1)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(default=None)),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('is_delivery_fees', models.BooleanField(default=None)),
                ('on_sale', models.BooleanField(default=True)),
                ('last_bidder_1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bidder_1', to=settings.AUTH_USER_MODEL)),
                ('last_bidder_2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bidder_2', to=settings.AUTH_USER_MODEL)),
                ('last_bidder_3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bidder_3', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
