# Generated by Django 5.1.6 on 2025-02-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
