# Generated by Django 5.1.6 on 2025-02-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auctons',
        ),
    ]
