# Generated by Django 5.1.6 on 2025-03-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auctons_id_alter_auctons_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='last_bidder_1',
        ),
        migrations.RemoveField(
            model_name='items',
            name='last_bidder_2',
        ),
        migrations.RemoveField(
            model_name='items',
            name='last_bidder_3',
        ),
    ]
