# Generated by Django 5.1.6 on 2025-03-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_remove_items_last_price_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='item',
            new_name='item_Id',
        ),
    ]
